### PR TITLE
Add ability to set reviewers via command [sc-6303]

### PR DESCRIPTION
**Pull request by quanweilena**
plz-review-url: https://plz.review/review/2160

### CODE REVIEW

**Comment by trotterdylan** [comment]
1 new comment(s) @ https://www.plz.review/review/2160

**Review by trotterdylan — CHANGES_REQUESTED** [review]
This is great! Nice work. Just one suggestion.

**Comment by quanweilena** [comment]
1 new comment(s) @ https://www.plz.review/review/2160

**Review by quanweilena — COMMENTED** [review]
I'm so sorry that I forgot to submit my feedback after I updated this pr 😩

**Review by trotterdylan — CHANGES_REQUESTED** [review]
Looking good overall, just a few suggestions

**Comment by trotterdylan** [comment]
5 new comment(s) @ https://www.plz.review/review/2160

**Review by quanweilena — COMMENTED** [review]
5 new comment(s) @ https://www.plz.review/review/2160

**Review by trotterdylan — APPROVED** [review]
LGTM!

**Pull request merged**
